# Datenbank
spring.datasource.url=jdbc:postgresql://localhost:5432/presently
spring.datasource.username=presently_user
spring.datasource.password=presently123

# JPA/ Hibernate
# erstellt und aktualisiert die Tabellen automatisch (die Postgresql Tabellen)
spring.jpa.hibernate.ddl-auto=update
# zeigt im Terminal, welche SQL-Befehle Hibernate ausführt (Debugging)
spring.jpa.show-sql=true
# Hibernate redet mit PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=8080